// move to: https://p3d.in/u/BalaChuang

import PhotoSwipeLightbox from './PhotoSwipe_v5_core/photoswipe-lightbox.esm.js';

const imageHtml = '<a href="ImageFull/{name}.png" data-pswp-width="{w}" data-pswp-height="{h}" target="_blank"><img class="thumb-image" src="ImageThumb/{name}.jpg" alt="{desc}" /></a>';
const videoHtml = '<a href="VideoFull/{name}.png" data-pswp-width="{w}" data-pswp-height="{h}" target="_blank"><img class="thumb-image" src="VideoThumb/{name}.jpg" alt="{desc}" /></a>';

/*
 * Read imageList.txt and Generate DOM for Display
 * PS. The file "imageList.txt" is generated by "ThumbGen/gen.bat/ps1".
 *     This file should be re-gerenated when a new image is added.
 *     Full Images: ./Images/xxx.png
 *     Thumbnails:  ./Thumbnails/xxx.jpg (20% size of Full Images)
 * PS. SOP of Generating Images:
 *     1. Move Full-Size Image (*.png) into ./Images folder
 *     2. Generate Thumbnail (*.jpg, 20% size)
 *     3. Execute ./ImageGen/gen.bat to update imageList.txt
*/

$('#image-content').load('./ThumbGen/imageList.txt', '', function(fileContent, status) {
	var isUnixSplot = (fileContent.indexOf('\r\n') < 0);
	var contAry = isUnixSplot ? fileContent.split('\n') : fileContent.split('\r\n');
	var start = false;
	for (var i=0; i<contAry.length; ++i)
	{
		if (contAry[i].indexOf('---') >= 0) {
			start = true;
			continue;
		}
		if (($.trim(contAry[i]) === '') || !start) continue;

		var imgItem = contAry[i].split('\t');
		if (imgItem.length != 3) continue;

		var imgName = $.trim(imgItem[0]);
		var imgW = $.trim(imgItem[1]);
		var imgH = $.trim(imgItem[2]);
		var thisImage = imageHtml
			.replaceAll('{name}', imgName)
			.replaceAll('{w}', imgW)
			.replaceAll('{h}', imgH)
			.replaceAll('{desc}', imgName);
		$('#my-images').append(thisImage);
	}
	// initPhotoSwipe();
});

// Create PhotoSwipe object
function initPhotoSwipe() {
	const lightbox = new PhotoSwipeLightbox({
		gallery: '#my-images',
		children: 'a',
		showHideAnimationType: 'fade',
		pswpModule: () => import('./PhotoSwipe_v5_core/photoswipe.esm.js')
	});
	lightbox.init();
}
