import PhotoSwipeLightbox from './PhotoSwipe_v5_core/photoswipe-lightbox.esm.js';

// Read imageList.txt and Generate DOM for Display
// PS. The file "imageList.txt" is generated by "ImagesGen/getImages.bat/ps1".
//     This file should be re-gerenated when a new image is added.
//     Full Images: ./images/xxx.png
//     Thumbnails:  ./images/xxx.jpg (20% size of Full Images)
const imgHtml = '<a href="{name}.png" data-pswp-width="{w}" data-pswp-height="{h}" target="_blank"> <img class="thumb-image" src="{name}.jpg" alt="{desc}" /></a>';
$('#image-content').load('./ImagesGen/imageList.txt', '', function(fileContent, status){
	var isUnixSplot = (fileContent.indexOf('\r\n') < 0);
	var contAry = isUnixSplot ? fileContent.split('\n') : fileContent.split('\r\n');
	var start = false;
	for (var i=0; i<contAry.length; ++i)
	{
		if (contAry[i].indexOf('---') >= 0) {
			start = true;
			continue;
		}
		if (($.trim(contAry[i]) === '') || !start) continue;

		var imgItem = contAry[i].split('\t');
		if (imgItem.length != 3) continue;

		var imgFName = $.trim(imgItem[0]);
		var imgW = $.trim(imgItem[1]);
		var imgH = $.trim(imgItem[2]);
		var thisImg = imgHtml
			.replaceAll('{name}', 'Images/' + imgFName)
			.replaceAll('{w}', imgW)
			.replaceAll('{h}', imgH)
			.replaceAll('{desc}', imgFName);
		$('#my-3d-gallery').append(thisImg);
	}
	initPhotoSwipe();
});

// Create PhotoSwipe object
function initPhotoSwipe() {
	const lightbox = new PhotoSwipeLightbox({
		gallery: '#my-3d-gallery',
		children: 'a',
		pswpModule: () => import('./PhotoSwipe_v5_core/photoswipe.esm.js')
	});
	lightbox.init();
}
